---
# Source: prometheus/templates/services/server.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    component: server
  name: prometheus
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
  sessionAffinity: None
  type: ClusterIP
