---
# Source: prometheus/templates/services/server.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  ports:
  - name: server
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: pushgw
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
