apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/thestormforge/examples/postgres

## Need to change strategy here since we're limited to 2cpu total
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: postgres
  spec:
    strategy:
      type: Recreate
