apiVersion: v1
kind: Service
metadata:
  name: cost-model
spec:
  selector:
    app: cost-model
  ports:
    - name: cost-model
      port: 9003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-model
spec:
  selector:
    matchLabels:
      app: cost-model
  template:
    metadata:
      labels:
        app: cost-model
    spec:
      serviceAccountName: redsky
      restartPolicy: Always
      containers:
        - name: cost-model
          image: ajaytripathy/kubecost-cost-model
          resources:
            requests:
              cpu: "10m"
              memory: "55M"
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "http://prometheus:9090"
            - name: CLOUD_PROVIDER_API_KEY
              value: "AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U"

