apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  replicas: 4
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      initContainers:
      - name: init-data
        image: alpine
        command: ["/bin/sh"]
        args: ["-c","in=$(bzip2 -dc /var/spool/filebeat-seed-data.txt.bz2) && ( while true ; do printf \"$in\" ; done ) | head -c 400m > /var/log/loadgen/logfile.txt"]
        volumeMounts:
          - name: data
            mountPath: /var/log/loadgen/
          - name: config
            mountPath: /var/spool/filebeat-seed-data.txt.bz2
            subPath: filebeat-seed-data.txt.bz2
      containers:
      - image: docker.elastic.co/beats/filebeat:6.7.1
        name: filebeat
        volumeMounts:
          - name: data
            mountPath: /var/log/loadgen/
          - name: config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat-config.yaml
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: filebeat
