terminationGracePeriodSeconds: 5

podManagementPolicy: Parallel

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 20
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 20
  successThreshold: 1

persistence:
  enabled: false

elasticsearch:
  host: elasticsearch-client

inputs:
  main: |-
    input {
      beats {
        codec => json
        port => 5044
      }
    }

outputs:
  main: |-
    output {
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
        manage_template => false
        index => "logstash-index"
        document_type => "%{[@metadata][type]}"
      }
    }
