apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
  - name: http
    port: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'elk'
        static_configs:
        - targets:
          - "kube-state-metrics:8080"
          - "node-exporter:9100"
          - "cost-model:9003"
          - "elasticsearch-exporter:9108"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: redsky
      volumes:
        - name: config
          configMap:
            name: prometheus-config
      containers:
        - name: prometheus
          image: "prom/prometheus"
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
