name: Main workflow
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_METADATA: build.${{ github.run_number }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Fetch tags
        run: git fetch --depth=1 origin '+refs/tags/*:refs/tags/*'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Cache Go Modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
        with:
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      - name: Bootstrap
        run: |
          if [ -z "${GITHUB_REF/refs\/tags\/*/}" ]; then
            echo "::set-env name=VERSION::${GITHUB_REF##*/}"
            TAG=${GITHUB_REF##*/v}
            DOCKER_TAG=latest
          else
            TAG=${GITHUB_SHA:0:8}.${GITHUB_RUN_NUMBER}
            DOCKER_TAG=canary
          fi
          echo "::set-env name=IMG::gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/redskyops-controller:${TAG}"
          echo "::set-env name=REDSKYCTL_IMG::gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/redskyctl:${TAG}"
          echo "::set-env name=SETUPTOOLS_IMG::gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/setuptools:${TAG}"
          echo "::set-env name=PULL_POLICY::Always"
          echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
          gcloud --quiet auth configure-docker
      - name: Build controller
        run: |
          make docker-build
          make docker-push
      - name: Build tool
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --rm-dist --release-notes hack/changelog.md.txt
          key: ${{ secrets.BMASTERS_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.BMASTERS_TOKEN }}
      - name: Tag Docker images
        run: |
          docker tag "${IMG}" "${IMG%%:*}:${DOCKER_TAG}"
          docker push "${IMG%%:*}:${DOCKER_TAG}"
          docker tag "${REDSKYCTL_IMG}" "${REDSKYCTL_IMG%%:*}:${DOCKER_TAG}"
          docker push "${REDSKYCTL_IMG%%:*}:${DOCKER_TAG}"
          docker tag "${SETUPTOOLS_IMG}" "${SETUPTOOLS_IMG%%:*}:${DOCKER_TAG}"
          docker push "${SETUPTOOLS_IMG%%:*}:${DOCKER_TAG}"
      - name: Upload macOS binary
        uses: actions/upload-artifact@v1
        with:
          name: redskyctl_darwin_amd64
          path: dist/redskyctl-darwin-amd64.tar.gz
      - name: Upload Linux binary
        uses: actions/upload-artifact@v1
        with:
          name: redskyctl_linux_amd64
          path: dist/redskyctl-linux-amd64.tar.gz
