name: Pull Request workflow
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_METADATA: pr.${{ github.actor }}.${{ github.run_id }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Set up Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
        with:
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      - name: Bootstrap
        run: |
          TAG=${GITHUB_SHA:0:8}.${GITHUB_RUN_ID}
          echo "::set-env name=IMG::gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/redskyops-controller:${TAG}"
          echo "::set-env name=REDSKYCTL_IMG::gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/redskyctl:${TAG}"
          echo "::set-env name=SETUPTOOLS_IMG::gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/setuptools:${TAG}"
          echo "::set-env name=PULL_POLICY::Always"
          gcloud --quiet auth configure-docker

          # kubebuilder
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin
      - name: Build controller
        run: |
          make docker-build
          make docker-push
      - name: Build tool
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --skip-sign --rm-dist
      - name: Upload macOS binary
        uses: actions/upload-artifact@v1
        with:
          name: redskyctl_darwin_amd64
          path: dist/redskyctl_darwin_amd64
      - name: Upload Linux binary
        uses: actions/upload-artifact@v1
        with:
          name: redskyctl_linux_amd64
          path: dist/redskyctl_linux_amd64
