name: Pull Request workflow
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_METADATA: pr.${{ github.run_number }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Fetch tags
        run: git fetch --depth=1 origin '+refs/tags/*:refs/tags/*'
      - name: Verify Header
        uses: talos-systems/conform@v0.1.0-alpha.19
      - name: Docker Cache (controller)
        uses: actions/cache@v1
        with:
          path: controllercache
          key: ${{ runner.os }}-controllercache-${{ hashFiles('**/dockercache') }}
          restore-keys: |
            ${{ runner.os }}-controllercache-
      - name: Docker Cache (tools)
        uses: actions/cache@v1
        with:
          path: toolscache
          key: ${{ runner.os }}-toolscache-${{ hashFiles('**/toolscache') }}
          restore-keys: |
            ${{ runner.os }}-toolscache-
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Docker Buildx (build)
        run: |
          make -f Makefile.ci docker-build
      #- name: Docker buildx (push)
      #  run: |
      #    make -f Makefile.ci docker-push
